--------------------------------------------------------
--  File created - Wednesday-April-18-2018   
--------------------------------------------------------
DROP TABLE "LZHU"."BANK_USER" cascade constraints;
--------------------------------------------------------
--  DDL for Table BANK_USER
--------------------------------------------------------

  CREATE TABLE "LZHU"."BANK_USER" 
   (	"ACCOUNT" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"SSN" NUMBER, 
	"PASSWORD" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LZHU.BANK_USER
SET DEFINE OFF;
Insert into LZHU.BANK_USER (ACCOUNT,TYPE,SSN,PASSWORD,EMAIL) values (12345,'saving',123,123,'123');
Insert into LZHU.BANK_USER (ACCOUNT,TYPE,SSN,PASSWORD,EMAIL) values (1222,'saving',123,123,'hello');
Insert into LZHU.BANK_USER (ACCOUNT,TYPE,SSN,PASSWORD,EMAIL) values (0,'Savings',0,0,'00');
Insert into LZHU.BANK_USER (ACCOUNT,TYPE,SSN,PASSWORD,EMAIL) values (417,'Savings',888,888,'lzhu@gmail.com');
Insert into LZHU.BANK_USER (ACCOUNT,TYPE,SSN,PASSWORD,EMAIL) values (11,'Savings',11,11,'11');
Insert into LZHU.BANK_USER (ACCOUNT,TYPE,SSN,PASSWORD,EMAIL) values (20170417,'Savings',99999,999,'lzhu5@stevens.edu');
Insert into LZHU.BANK_USER (ACCOUNT,TYPE,SSN,PASSWORD,EMAIL) values (111,'Savings',111,111,'evezhu@gmail.com');
Insert into LZHU.BANK_USER (ACCOUNT,TYPE,SSN,PASSWORD,EMAIL) values (890,'Savings',888,888,'lzhu@stevens.edu');
--------------------------------------------------------
--  DDL for Index BANK_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LZHU"."BANK_USER_PK" ON "LZHU"."BANK_USER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BANK_USER
--------------------------------------------------------

  ALTER TABLE "LZHU"."BANK_USER" ADD CONSTRAINT "BANK_USER_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LZHU"."BANK_USER" MODIFY ("EMAIL" NOT NULL ENABLE);
