--------------------------------------------------------
--  File created - Wednesday-April-18-2018   
--------------------------------------------------------
DROP TABLE "LZHU"."BANK_ACCOUNT" cascade constraints;
--------------------------------------------------------
--  DDL for Table BANK_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "LZHU"."BANK_ACCOUNT" 
   (	"ACCOUNT" NUMBER, 
	"AMOUNT" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LZHU.BANK_ACCOUNT
SET DEFINE OFF;
Insert into LZHU.BANK_ACCOUNT (ACCOUNT,AMOUNT,NAME) values (11,333,'11');
Insert into LZHU.BANK_ACCOUNT (ACCOUNT,AMOUNT,NAME) values (20170417,999,'lin zhu');
Insert into LZHU.BANK_ACCOUNT (ACCOUNT,AMOUNT,NAME) values (111,12252,'evelyn');
Insert into LZHU.BANK_ACCOUNT (ACCOUNT,AMOUNT,NAME) values (890,79748,'li');
--------------------------------------------------------
--  DDL for Index BANK_ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LZHU"."BANK_ACCOUNT_PK" ON "LZHU"."BANK_ACCOUNT" ("ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "LZHU"."BANK_ACCOUNT" ADD CONSTRAINT "BANK_ACCOUNT_PK" PRIMARY KEY ("ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LZHU"."BANK_ACCOUNT" MODIFY ("ACCOUNT" NOT NULL ENABLE);
